eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: configserver
server:
  port: 8085
spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TranQuangPhong/springboot-hellomicro-config-server
          default-label: main
          clone-on-start: true
      discovery:
        serviceId: configserver
