version: '2'
services:
  mysql:
    image: mysql:8.0.27
    ports:
      - 3306:3306
    volumes:
      - ./volume_1:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=phong
      - MYSQL_PASSWORD=phong
      - MYSQL_DATABASE=db_hello
# volumes:
#   volume_1:
    # driver_opts:
    #   device: ./volumes/volume_1
    #   type: bind