version: '2'
services:
  redis:
    image: redis
    command: redis-server --requirepass password123
    ports:
      - 6379:6379
    volumes:
      - ./volume:/data
    environment:
      - REDIS_PASSWORD=password123
      - REDIS_PORT_NUMBER=6379
